[features]
seeds = false
skip-lint = false
[programs.localnet]
audius_project = "GVi4HHgQ4eSfiidepQtEmNBwLgz5kQsUiwzW6iUKuvSy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leandrofaria/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
